apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstorages.epca.eo
spec:
  group: epca.eo
  names:
    kind: XStorage
    plural: xstorages
  claimNames:
    kind: Storage
    plural: storages
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Specifications for the XStorage Crossplane Composition.
              properties:
                buckets:
                  type: array
                  description: List of buckets to be created.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the bucket.
                      owner:
                        type: string
                        description: Owner of the bucket.
                  required:
                    - name
                    - owner
                providerConfig:
                  type: string
              required:
                - buckets
                - providerConfig
